---
- name: PARSE SHOW VERSION
  hosts: cisco
  gather_facts: no
  connection: network_cli

  roles:
    - parse_genie

  tasks:
    - name: SHOW VERSION
      ios_command:
        commands:
          - show version
      register: version

    - name: SET FACT GENIE FILTER
      set_fact: 
        pyats_version: "{{ version['stdout'][0] | parse_genie(command='show version', os='ios') }}"

    - name: DEBUG PYATS FACTS
      debug:
        var: pyats_version
